"""01 ground-truth forensics. Writes 01_GROUND_TRUTH_FORENSICS.md.

usage: python gt_forensics.py <dataset_dir> <out_md>
"""
import sys

import numpy as np
import pandas as pd

from io_utils import load_gt_pairs, load_source

data, out = sys.argv[1], sys.argv[2]
L = ["# 01 — Ground-Truth Forensics", "",
     "Generated by `code/business_entity_resolution/src/gt_forensics.py`. Every number below is computed and none is hand-typed.", ""]
gt, pairs = load_gt_pairs(data)
s1 = load_source(data, "train", 1)
s2 = load_source(data, "train", 2)
s3 = load_source(data, "train", 3)

# --- integrity -------------------------------------------------------------
L += ["## Integrity", ""]
gs, fs = set(gt.source1_entity_id.tolist()), set(s1.entity_id.tolist())
L.append(f"- GT S1 IDs == train_source1 IDs: **{gs == fs}** (GT-only {len(gs-fs)}, file-only {len(fs-gs)})")
ids2, ids3 = set(s2.entity_id.tolist()), set(s3.entity_id.tolist())
pre = pairs.m.str[:3]
miss2 = (~pairs.m[pre == "S2-"].isin(ids2)).sum(); miss3 = (~pairs.m[pre == "S3-"].isin(ids3)).sum()
L.append(f"- listed IDs by prefix: {pre.value_counts().to_dict()}; S2 IDs absent from train_source2: {miss2}; S3 absent from train_source3: {miss3}")
L.append(f"- listed IDs unique across all rows: **{pairs.m.is_unique}** (one S2/S3 record → at most one S1)")
un2 = len(ids2 - set(pairs.m)); un3 = len(ids3 - set(pairs.m))
L.append(f"- never-matched (distractor) records: S2 {un2:,} / {len(ids2):,} ({100*un2/len(ids2):.1f}%), S3 {un3:,} / {len(ids3):,} ({100*un3/len(ids3):.1f}%)")
L.append("")

# --- per-S1 structure -------------------------------------------------------
pairs["src"] = pairs.m.str[:2]
cnt = pairs.groupby(["s1", "src"]).size().unstack(fill_value=0).reindex(s1.entity_id.tolist(), fill_value=0)
cnt.columns = [c for c in cnt.columns]
n2, n3 = cnt.get("S2", 0), cnt.get("S3", 0)
tot = n2 + n3
kind = np.select([tot == 0, (n2 > 0) & (n3 == 0), (n2 == 0) & (n3 > 0)], ["singleton", "S2-only", "S3-only"], "both")
per = pd.DataFrame({"s1": cnt.index, "n2": n2.values, "n3": n3.values, "n": tot.values, "kind": kind})
per = per.merge(s1.rename(columns={"entity_id": "s1"}), on="s1")
N = len(per)
L += ["## Match-count distribution (all S1)", "", "| bucket | S1 count | share |", "|---|---|---|"]
b = pd.cut(per.n, [-1, 0, 1, 2, 3, 100], labels=["0", "1", "2", "3", "4+"])
for k, v in b.value_counts().sort_index().items():
    L.append(f"| {k} | {v:,} | {100*v/N:.2f}% |")
L += ["", "| source mix | S1 count | share |", "|---|---|---|"]
for k, v in per.kind.value_counts().items():
    L.append(f"| {k} | {v:,} | {100*v/N:.2f}% |")
L += ["", "### Joint (#S2 matches × #S3 matches), S1 counts", ""]
jt = pd.crosstab(per.n2.clip(upper=6), per.n3.clip(upper=6))
L.append("| #S2 \\ #S3 | " + " | ".join(f"{c}{'+' if c == 6 else ''}" for c in jt.columns) + " |")
L.append("|---" * (len(jt.columns) + 1) + "|")
for r, row in jt.iterrows():
    L.append(f"| {r}{'+' if r == 6 else ''} | " + " | ".join(f"{v:,}" for v in row.values) + " |")
L += ["", f"- S1 with ≥2 S2 matches: {(per.n2 >= 2).sum():,} ({100*(per.n2 >= 2).mean():.1f}%); with ≥2 S3 matches: {(per.n3 >= 2).sum():,} ({100*(per.n3 >= 2).mean():.1f}%)",
      f"- mean matches per S1: {per.n.mean():.3f}; per non-singleton S1: {per.n[per.n > 0].mean():.3f}", ""]

L += ["## By country", "", "| country | S1 | singleton % | mean #S2 | mean #S3 | mean total | S2-only % | S3-only % | both % |", "|---|---|---|---|---|---|---|---|---|"]
for c, g in per.groupby("country"):
    L.append(f"| {c} | {len(g):,} | {100*(g.n == 0).mean():.2f} | {g.n2.mean():.3f} | {g.n3.mean():.3f} | {g.n.mean():.3f} | "
             f"{100*(g.kind == 'S2-only').mean():.2f} | {100*(g.kind == 'S3-only').mean():.2f} | {100*(g.kind == 'both').mean():.2f} |")
L.append("")

# --- country agreement on true pairs ---------------------------------------
pool = pd.concat([s2, s3], ignore_index=True).rename(columns={"entity_id": "m", "business_name": "m_name", "business_address": "m_addr", "country": "m_country"})
pp = pairs.merge(per[["s1", "business_name", "business_address", "country", "n"]], on="s1").merge(pool, on="m", how="left")
agree = (pp.country == pp.m_country).mean()
L += ["## Country-label agreement on true pairs", "",
      f"- share of true pairs whose S2/S3 country label equals the S1 label: **{100*agree:.4f}%** "
      f"({(pp.country != pp.m_country).sum():,} disagreements)"]
if (pp.country != pp.m_country).any():
    L.append(f"- disagreement examples: {pp.loc[pp.country != pp.m_country, ['s1','country','m','m_country']].head(5).values.tolist()}")
L += ["- implication: country can be used as a **hard block key** only if this is 100%, and even then only because the label is given on every test row (France included). Treat unknown/new labels as their own block.", ""]

# distractor country mix
unm = pool[~pool.m.isin(pairs.m)]
L += [f"- distractor country mix: {unm.m_country.value_counts().to_dict()}", ""]

# --- ID / row-order leakage probes -------------------------------------------
L += ["## ID / file-order leakage probes", ""]
num = lambda s: s.str[3:].astype(np.int64)
pp_ = pp[["s1", "m"]].copy()
pp_["a"] = num(pp_.s1); pp_["b"] = num(pp_.m)
rho = pp_[["a", "b"]].rank().corr().iloc[0, 1]
L.append(f"- Spearman(S1 id number, matched id number) over true pairs: {rho:.4f}")
pos2 = pd.Series(np.arange(len(s2)), index=s2.entity_id.tolist()); pos1 = pd.Series(np.arange(len(s1)), index=s1.entity_id.tolist())
p2 = pp_[pp_.m.str.startswith("S2")]
rr = pd.Series(pos1.reindex(p2.s1).values).corr(pd.Series(pos2.reindex(p2.m).values), method="spearman")
L.append(f"- Spearman(S1 file row, matched S2 file row): {rr:.4f}")
# do cluster-mates sit next to each other in the S2 file?
p2 = p2.assign(r=pos2.reindex(p2.m).values)
spread = p2.groupby("s1").r.agg(lambda x: x.max() - x.min() if len(x) > 1 else np.nan).dropna()
L.append(f"- row-distance between S2 cluster-mates in the S2 file: median {spread.median():,.0f}, p1 {spread.quantile(.01):,.0f} (random expectation ≈ {len(s2)/3:,.0f})")
L.append("- verdict: an ID or row-order leak exists only if a value above is far from 0 or the spread is far below random. Interpretation is in 03_LEAKAGE_AUDIT.md.")
L.append("")

# --- examples ----------------------------------------------------------------
rng = np.random.RandomState(7)
def show(title, ids):
    L.extend([f"### {title}", ""])
    for sid in ids:
        r = per[per.s1 == sid].iloc[0]
        L.append(f"- **{sid}** [{r.country}] `{r.business_name}` | `{r.business_address}`")
        for _, m in pp[pp.s1 == sid].iterrows():
            L.append(f"  - {m.m} [{m.m_country}] `{m.m_name}` | `{m.m_addr}`")
    L.append("")
L += ["## Examples (random, seed 7)", ""]
for lab, mask in [("0 matches (singleton)", per.n == 0), ("1 match", per.n == 1), ("2 matches", per.n == 2),
                  ("3 matches", per.n == 3), ("4+ matches", per.n >= 4), ("S2-only", per.kind == "S2-only"),
                  ("S3-only", per.kind == "S3-only"), ("max-size clusters (≥10)", per.n >= 10)]:
    for c in sorted(per.country.unique()):
        ids = per.s1[mask & (per.country == c)]
        if len(ids):
            show(f"{lab} — {c}", ids.sample(min(3, len(ids)), random_state=rng).tolist())

pp.to_parquet(out.replace(".md", "_pairs.parquet")) if len(sys.argv) > 3 else None
open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("done")
