"""Render 00_DATASET_INVENTORY.md from the per-file JSON produced by inventory.py."""
import json
import os
import sys

inv_dir, root = sys.argv[1], sys.argv[2]
role = {'train_source1': 'train Source 1 (reference)', 'train_source2': 'train Source 2',
        'train_source3': 'train Source 3', 'train_ground_truth': 'train ground truth',
        'test_source1': 'test Source 1 (predict every row)', 'test_source2': 'test Source 2',
        'test_source3': 'test Source 3'}
order = list(role)
D = {k: json.load(open(os.path.join(inv_dir, f'inv_{k}.json'), encoding='utf-8')) for k in order}


def esc(x):
    return str(x).replace('|', '\\|')


L = ["# 00 — Dataset Inventory", "",
     "Generated by `code/business_entity_resolution/src/inventory.py` (one process per file) and "
     "`inventory_report.py`. All reads use `sep=\"\\t\"`, `quoting=QUOTE_NONE`, `dtype=string[pyarrow]`, "
     "`keep_default_na=False` and `na_filter=False`. Raw line counts are taken without pandas and compared to the parsed row counts.", "",
     "## TSV parsing verdict", "",
     "| file | raw lines−1 | parsed rows | diff | header tabs | cols with `\\t` | cols if parsed as CSV |",
     "|---|---|---|---|---|---|---|"]
for k in order:
    d = D[k]
    L.append(f"| {k}.tsv | {d['raw_lines_incl_header']-1:,} | {d['rows']:,} | {d['rows_vs_lines_diff']} | "
             f"{d['header_tab_count']} | {d['cols']} | {d['header_if_parsed_as_csv']} |")
L += ["", "**PASS.** Every file parses into the expected number of columns with `sep=\"\\t\"`. No rows are lost "
      "(diff = 0 everywhere, so there are no embedded newlines or quote-swallowed rows). Parsed as CSV, every header "
      "collapses to **1 column**, which is the documented failure mode.", ""]
L += ["## File table", "", "| role | path | rows | cols | size |", "|---|---|---|---|---|"]
for k in order:
    d = D[k]
    L.append(f"| {role[k]} | `{d['path']}` | {d['rows']:,} | {d['cols']} | "
             f"{os.path.getsize(os.path.join(root, d['path']))/1e6:.0f} MB |")
L += ["", "## Per-file detail", ""]
for k in order:
    d = D[k]
    L += [f"### {k}.tsv — {role[k]}", ""]
    L.append(f"- columns: `{d['columns']}`; dtypes: all `string` (read as str on purpose; IDs are never cast to int)")
    L.append(f"- null per column: {d['null']}")
    L.append(f"- blank-string (after strip) per column: {d['blank']}")
    L.append(f"- leading/trailing whitespace: {d['lead_trail_ws']}")
    L.append(f"- whole-field literal null-ish tokens (`nan/null/none/na/n/a/-`): {d['literal_nullish']}")
    L.append(f"- duplicate full rows: {d['dup_rows_full']}; duplicate IDs: {d['dup_first_col']}")
    if 'dup_rows_excl_id' in d:
        L.append(f"- duplicate rows ignoring ID (same name+addr+country, different ID): **{d['dup_rows_excl_id']:,}**")
        L.append(f"- ID prefixes: {d['id_prefixes']}; malformed IDs (not `S[123]-\\d+`): {d['malformed_ids']}; "
                 f"leading-zero numeric part: {d['id_leading_zero']}")
        L.append(f"- ID numeric-part length distribution: {d['id_num_len']}. IDs are **variable-length**, so never zero-pad or cast them.")
        L.append(f"- country: {d['country']}")
        L.append(f"- name length min/p50/p99/max: {d['name_len_q']}; address length: {d['addr_len_q']}")
        L.append(f"- one-char name: {d['name_one_char']}; one-char address: {d['addr_one_char']}; both blank: {d['both_blank']}")
        L.append("- per country (n / blank name / blank address):")
        for c, v in d['per_country'].items():
            L.append(f"  - {c}: {v['n']:,} / {v['blank_name']} / {v['blank_addr']:,}")
        L += ["- sample rows (6 random, then 3 per country):", "",
              "| entity_id | business_name | business_address | country |", "|---|---|---|---|"]
        for r in d['sample'] + [r for v in d['per_country'].values() for r in v['sample']]:
            L.append("| " + " | ".join(esc(x) for x in r) + " |")
    else:
        L.append(f"- malformed S1 IDs: {d['malformed_ids']}; malformed listed IDs (not `S[23]-\\d+`): {d['malformed_list_ids']}")
        L.append(f"- list length distribution: {d['list_len_dist']}")
        L.append(f"- listed IDs: {d['list_ids_total']:,}; unique: {d['list_ids_unique']:,}. **Every S2/S3 ID is claimed by at most one S1.** "
                 f"IDs with stray whitespace: {d['list_ids_with_space']}; intra-list duplicates: {d['intra_list_dupes']}")
        L += ["- sample rows:", "", "| source1_entity_id | matched_entity_ids |", "|---|---|"]
        for r in d['sample']:
            L.append(f"| {r[0]} | {r[1]} |")
    L.append("")

gt = D['train_ground_truth']
S23 = D['train_source2']['rows'] + D['train_source3']['rows']
n_list = gt['list_ids_total']
t1 = D['test_source1']
L += ["## Findings that change the plan", "",
      f"1. **Scale.** The train pool (S2+S3) has {S23:,} records against {D['train_source1']['rows']:,} S1. The test pool has "
      f"{D['test_source2']['rows']+D['test_source3']['rows']:,} against {t1['rows']:,} S1. Any all-pairs step is impossible, so blocking "
      "must be sub-quadratic and fit in 16 GB RAM.",
      f"2. **GT exclusivity.** {n_list:,} listed IDs, all unique, so no S2/S3 record belongs to two S1. That is a hard structural "
      "constraint to enforce at decision time (one S2/S3 → at most one S1).",
      f"3. **Distractors.** {S23-n_list:,} train S2+S3 records ({100*(S23-n_list)/S23:.1f}%) are not listed for any S1 "
      "(the check that all listed IDs exist is in 01).",
      f"4. **Singletons are rare:** {gt['list_len_dist']['0']:,} / {gt['rows']:,} = {100*gt['list_len_dist']['0']/gt['rows']:.2f}%. "
      "Macro-F0.5 is dominated by multi-match S1 (mode 3 matches, max 11), so recall inside a cluster matters more than the brief's singleton emphasis implies.",
      "5. **Blank addresses appear only in S2/S3** (about 3% of rows in every country, France included). S1 has no blanks. "
      "Names are never blank, but a few are literal `nan/null/NA` strings (6–61 per file); a default `pd.read_csv` would turn them into NaN.",
      "6. **Exact duplicate (name, address, country) records with different IDs** exist inside S2 and S3 (16k–26k per file). "
      "03 checks whether both copies sit in the same GT cluster.",
      "7. **Native-script text** appears in India S2/S3 names and addresses (Devanagari, Tamil, Telugu, Kannada, Bengali, Gujarati), including "
      "state names. Latin-only char n-grams cannot retrieve these, so transliteration is required. It has to be written in-house, because `unidecode` is GPL.",
      "8. **Injected junk tokens** in S2/S3: `<<`, `>>`, `--`, `##`, `[Partners]`, `((Ltd))`, the literal `null` inside addresses, "
      "domain-style names (`unitedimpex.com`), word-order swaps, and typos (`Inevstmmnnt`, `Phyismans`).",
      f"9. **France:** test S1 has {t1['country']['France']:,} French rows ({100*t1['country']['France']/t1['rows']:.1f}%). "
      "Training has none. The country mix also shifts: US is 60% of train S1 but 38% of test S1, and India goes from 40% to 47%.",
      "10. **Disk:** C: has about 880 MB free. That blocks caching features, installing LightGBM and possibly writing `candidate_pairs.tsv` (hundreds of MB).",
      ]
open(os.path.join(root, "00_DATASET_INVENTORY.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote", len(L), "lines")
