"""03 leakage audit. usage: python leakage_audit.py <dataset_dir> <out_md>"""
import sys

import numpy as np
import pandas as pd

from io_utils import load_gt_pairs, load_source

data, out = sys.argv[1], sys.argv[2]
gt, pairs = load_gt_pairs(data)
owner = pd.Series(pairs.s1.values, index=pairs.m.values)
L = ["# 03 — Leakage Audit", "", "Generated by `code/business_entity_resolution/src/leakage_audit.py`.", ""]


def cheap(s: pd.Series) -> pd.Series:
    """Vectorised cheap normalisation: lowercase, alnum tokens, single spaces."""
    return s.str.lower().str.replace(r"[^0-9a-zऀ-ൿ]+", " ", regex=True).str.strip()


tr = {k: load_source(data, "train", k) for k in (1, 2, 3)}

# ---- S1 repeats / near duplicates -------------------------------------------------
s1 = tr[1]
s1n, s1a = cheap(s1.business_name), cheap(s1.business_address)
L += ["## 1. Repeated / near-duplicate S1 entities (train)", ""]
L.append(f"- exact duplicate (name, address, country): {s1.duplicated(['business_name','business_address','country']).sum():,}")
L.append(f"- duplicate after cheap normalisation (name, address): {pd.DataFrame({'n': s1n, 'a': s1a}).duplicated().sum():,}")
vc = s1n.value_counts()
L.append(f"- S1 rows whose normalised **name** is shared with another S1: {int(vc[vc > 1].sum()):,} "
         f"({100*vc[vc > 1].sum()/len(s1):.2f}%); largest group: `{vc.index[0]}` × {vc.iloc[0]}")
L.append(f"  - top shared names: " + ", ".join(f"`{k}` {v}" for k, v in vc.head(12).items()))
va = s1a.value_counts()
L.append(f"- S1 rows whose normalised **address** is shared with another S1: {int(va[va > 1].sum()):,} "
         f"({100*va[va > 1].sum()/len(s1):.2f}%); largest group ×{va.iloc[0]} `{va.index[0]}`")
L.append("  - top shared addresses: " + ", ".join(f"`{k}` {v}" for k, v in va.head(8).items()))
# how do singletons relate to name-sharing?
sing = set(gt.source1_entity_id[gt.matched_entity_ids == ""].tolist())
shared_name = s1n.map(vc) > 1
is_sing = s1.entity_id.isin(sing)
L.append(f"- singleton rate among S1 with a shared name: {100*is_sing[shared_name].mean():.2f}% vs unique name: {100*is_sing[~shared_name].mean():.2f}%")
shared_addr = s1a.map(va) > 1
L.append(f"- singleton rate among S1 with a shared address: {100*is_sing[shared_addr].mean():.2f}% vs unique address: {100*is_sing[~shared_addr].mean():.2f}%")
L.append("")

# ---- duplicate pool records: same cluster? ----------------------------------------
L += ["## 2. Duplicate S2/S3 records (train): do exact copies share a cluster?", "", "| file | dup groups (name+addr+country) | records in groups | groups all same owner | groups all unmatched | groups mixed (different S1 or matched+unmatched) |", "|---|---|---|---|---|---|"]
for k in (2, 3):
    d = tr[k]
    key = d.business_name + "\t" + d.business_address + "\t" + d.country
    dup = key.duplicated(keep=False)
    g = pd.DataFrame({"key": key[dup], "own": owner.reindex(d.entity_id[dup]).fillna("NONE").values})
    agg = g.groupby("key").own.agg(lambda x: "same" if x.nunique() == 1 and x.iloc[0] != "NONE" else ("none" if (x == "NONE").all() else "mixed"))
    vc2 = agg.value_counts()
    L.append(f"| train S{k} | {len(agg):,} | {int(dup.sum()):,} | {vc2.get('same', 0):,} | {vc2.get('none', 0):,} | {vc2.get('mixed', 0):,} |")
L.append("")
L.append("A *mixed* group means two byte-identical records have different labels. No model can separate those, which puts a hard ceiling on precision for them.")
L.append("")

# ---- cross-source identical text --------------------------------------------------
L += ["## 3. Identical text across sources", ""]
for k in (2, 3):
    d = tr[k]
    j = d.merge(s1, on=["business_name", "business_address", "country"], suffixes=("", "_s1"))
    ok = np.mean(np.asarray(owner.reindex(j.entity_id).fillna("").astype(object)) == np.asarray(j.entity_id_s1.astype(object))) if len(j) else float("nan")
    L.append(f"- train S{k} records byte-identical (name, addr, country) to some S1: {len(j):,}; share whose owner is that S1: {100*ok:.2f}%")
L.append("")

# ---- same name many addresses / same address many names in the pool ---------------
L += ["## 4. Collision families in the train pool (S2+S3, cheap-normalised)", ""]
pool = pd.concat([tr[2], tr[3]], ignore_index=True)
pn, pa = cheap(pool.business_name), cheap(pool.business_address)
own = owner.reindex(pool.entity_id).fillna("NONE").values
f = pd.DataFrame({"n": pn, "a": pa, "own": own})
gname = f[f.a != ""].groupby("n").agg(addrs=("a", "nunique"), owners=("own", "nunique"))
gaddr = f[f.a != ""].groupby("a").agg(names=("n", "nunique"), owners=("own", "nunique"))
L.append(f"- normalised names appearing with ≥5 distinct addresses: {(gname.addrs >= 5).sum():,}; with ≥5 distinct owners: {(gname.owners >= 5).sum():,}")
L.append(f"  - worst: " + ", ".join(f"`{k}` ({r.addrs} addrs, {r.owners} owners)" for k, r in gname.sort_values('owners', ascending=False).head(8).iterrows()))
L.append(f"- normalised addresses appearing with ≥5 distinct names: {(gaddr.names >= 5).sum():,}; with ≥3 distinct owners: {(gaddr.owners >= 3).sum():,}")
L.append(f"  - worst: " + ", ".join(f"`{k}` ({r.names} names, {r.owners} owners)" for k, r in gaddr.sort_values('owners', ascending=False).head(6).iterrows()))
L.append("")

# ---- train/test overlap ----------------------------------------------------------
del pool, pn, pa, f, gname, gaddr
import gc; gc.collect()
L += ["## 5. Train ↔ test overlap", ""]
te = {}
for k in (1, 2, 3):
    te[k] = load_source(data, "test", k)
    ids = set(tr[k].entity_id.tolist()) & set(te[k].entity_id.tolist())
    j = tr[k].merge(te[k], on=["business_name", "business_address", "country"])
    L.append(f"- source {k}: shared entity_ids {len(ids):,}; byte-identical (name, addr, country) records train↔test: {len(j):,}")
    if k > 1:
        del te[k], tr[k]; gc.collect()
s1tr_n = set(cheap(tr[1].business_name).tolist())
s1te_n = cheap(te[1].business_name)
L.append(f"- test S1 whose normalised name also occurs as a train S1 name: {100*s1te_n.isin(s1tr_n).mean():.2f}% "
         f"(US {100*s1te_n[te[1].country=='US'].isin(s1tr_n).mean():.2f}%, India {100*s1te_n[te[1].country=='India'].isin(s1tr_n).mean():.2f}%, France {100*s1te_n[te[1].country=='France'].isin(s1tr_n).mean():.2f}%)")
L.append("")

# ---- fold design -----------------------------------------------------------------
L += ["## 6. Validation design and why random pair splits are invalid", "",
      "- Folds are assigned per **S1 entity** (hash of the S1 ID, 5 folds). All candidate pairs of an S1 (true and false) go to its fold.",
      "- Pool records are exclusively owned (01: every S2/S3 is listed at most once), so a matched pool record can never be a positive in two folds.",
      "- Distractor pool records (26%) are unlabelled negatives. They appear as negative candidates for S1 in several folds; that is not leakage, because the model never sees a label that ties them to a validation S1.",
      "- A **random pair split** puts the positives of one S1 in both train and validation. The model then learns entity-specific name/address strings (`S1 name ↔ its own S2 variant`), and exclusivity/decision-layer features (rank of this pair within the S1, margin to the second candidate) are computed on information that crosses the split. It also cannot score entity-level F0.5, because a validation S1 has only part of its candidate set. Demonstration in the experiment ledger (EXP-LEAK).",
      "- **Label-derived normalisation is leakage.** The learned Indic→Latin token dictionary uses GT pairs, so it is fit only on the fixed dictionary fold (fold 0). Folds 1–4 are used for CV and fold 0 is never scored. IDF/DF statistics are label-free and fit transductively on all records of the split being processed (train for CV, test for inference), which is legitimate.",
      "- The threshold/decision layer is tuned on out-of-fold predictions only.", ""]
open(out, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("done")
